# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    providers:
        user_database:
            entity:
                class: AppBundle:User
    encoders:
        AppBundle\Entity\Blog\User:
            algorithm: bcrypt
            cost: 11

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: ~
            provider: user_database
            form_login:
               login_path: /login
               check_path: /login
            logout:
               path:   /logout
               target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
